DROP IF EXISTS TABLE  SudokuGrid
CREATE TABLE SudokuGrid
(i INTEGER NOT NULL
    CHECK (i BETWEEN 1 AND 9),
 j INTEGER NOT NULL
    CHECK (j BETWEEN 1 AND 9),
 val INTEGER NOT NULL
    CHECK (val BETWEEN 1 AND 9),
 region_nbr INTEGER NOT NULL,
    PRIMARY KEY (i, j, val));

CREATE TABLE Digits
 (digit INTEGER PRIMARY KEY); 

INSERT INTO Digits VALUES (1);
INSERT INTO Digits VALUES (2);
INSERT INTO Digits VALUES (3);
INSERT INTO Digits VALUES (4);
INSERT INTO Digits VALUES (5);
INSERT INTO Digits VALUES (6);
INSERT INTO Digits VALUES (7);
INSERT INTO Digits VALUES (8);
INSERT INTO Digits VALUES (9);