drop table if EXISTS SupParts;
CREATE TABLE SupParts
(sno INTEGER NOT NULL,
 pno INTEGER NOT NULL,
    PRIMARY KEY (sno, pno));

--1と3、2と4が一致する
INSERT INTO SupParts VALUES(1, 01);
INSERT INTO SupParts VALUES(1, 02);
INSERT INTO SupParts VALUES(1, 03);

INSERT INTO SupParts VALUES(2, 01);
INSERT INTO SupParts VALUES(2, 03);

INSERT INTO SupParts VALUES(3, 01);
INSERT INTO SupParts VALUES(3, 02);
INSERT INTO SupParts VALUES(3, 03);

INSERT INTO SupParts VALUES(4, 01);
INSERT INTO SupParts VALUES(4, 03);

INSERT INTO SupParts VALUES(5, 05);

INSERT INTO SupParts VALUES(6, 01);
INSERT INTO SupParts VALUES(6, 02);